version: "3.7"

volumes:
  postgres_data:
    name: omni.postgres_data

services:
  postgres:
    image: postgres:14.1-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always